/**
 * The cast: one art specification per character in the game.
 *
 * Gameplay stats live in `src/data`; this file only decides how a unit looks.
 * Adding a new unit is a matter of adding an entry here and a stat block in
 * the data layer.
 */
import type { CharacterSpec } from './humanoid';

/* ------------------------------------------------------- the human alliance */

export const DEFENDER_ART: Record<string, CharacterSpec> = {
  militia: {
    id: 'militia',
    height: 150,
    build: 'lean',
    skin: '#e8b48c',
    cloth: '#7d6a4f',
    accent: '#c9553f',
    eye: '#3b4a6b',
    head: { shape: 'round', ears: 'none', jaw: 'none', gear: 'cap', brow: -0.2, hair: '#6b4a2e' },
    weapon: 'spear',
    metal: '#9aa4b4',
  },
  archer: {
    id: 'archer',
    height: 152,
    build: 'lean',
    skin: '#f0c093',
    cloth: '#3f7a4e',
    accent: '#d8b24a',
    eye: '#2f5d3a',
    head: { shape: 'round', gear: 'hood', brow: -0.1, hair: '#8a5a2b' },
    weapon: 'bow',
  },
  guardian: {
    id: 'guardian',
    height: 158,
    build: 'broad',
    skin: '#e0a97c',
    cloth: '#3d4761',
    metal: '#aeb9c9',
    accent: '#2f6fb5',
    eye: '#2b3a5c',
    head: { shape: 'square', gear: 'full', brow: -0.3 },
    weapon: 'sword',
    offhand: 'shield',
  },
  arbalest: {
    id: 'arbalest',
    height: 154,
    build: 'lean',
    skin: '#dda17a',
    cloth: '#5a4470',
    metal: '#9aa4b4',
    accent: '#c99b3f',
    eye: '#3a2f52',
    head: { shape: 'round', gear: 'cap', brow: -0.15, hair: '#3a2a22' },
    weapon: 'crossbow',
  },
  cleric: {
    id: 'cleric',
    height: 152,
    build: 'lean',
    skin: '#f2c79e',
    cloth: '#f0ead8',
    accent: '#f2c14e',
    eye: '#5a7bb5',
    head: { shape: 'round', gear: 'hood', brow: -0.35, hair: '#c9a463' },
    weapon: 'staff',
    aura: '#ffe6a3',
  },
  frostmage: {
    id: 'frostmage',
    height: 150,
    build: 'lean',
    skin: '#ecc6a4',
    cloth: '#2f4f8a',
    accent: '#63cfe8',
    eye: '#63cfe8',
    head: { shape: 'long', gear: 'wizard', brow: -0.2, hair: '#dfe8f2' },
    weapon: 'staff',
    aura: '#8fe2f5',
  },
  pyromancer: {
    id: 'pyromancer',
    height: 152,
    build: 'lean',
    skin: '#e7b287',
    cloth: '#8c3222',
    accent: '#ff8c34',
    eye: '#ff8c34',
    head: { shape: 'long', gear: 'wizard', brow: 0.1, hair: '#c2452a' },
    weapon: 'staff',
    aura: '#ffb066',
  },
  paladin: {
    id: 'paladin',
    height: 168,
    build: 'broad',
    skin: '#e3ab7f',
    cloth: '#2c3a5e',
    metal: '#dfe6f0',
    accent: '#f2c14e',
    eye: '#4f7ac9',
    head: { shape: 'square', gear: 'plume', brow: -0.3 },
    weapon: 'greatsword',
    cape: '#c0392b',
  },
  monk: {
    id: 'monk',
    height: 156,
    build: 'broad',
    skin: '#c88a5c',
    cloth: '#c9762f',
    accent: '#f0d9a8',
    eye: '#4a3524',
    head: { shape: 'round', jaw: 'beard', brow: -0.2, hair: '#3a2a22' },
    weapon: 'hammer',
  },
};

/* ----------------------------------------------------------- the demon host */

export const ENEMY_ART: Record<string, CharacterSpec> = {
  goblin: {
    id: 'goblin',
    height: 118,
    build: 'small',
    skin: '#7db83f',
    cloth: '#6b4a2e',
    accent: '#c0392b',
    eye: '#f2d34e',
    head: { shape: 'long', ears: 'pointy', jaw: 'fangs', brow: 0.5 },
    weapon: 'dagger',
  },
  goblin_runner: {
    id: 'goblin_runner',
    height: 112,
    build: 'small',
    skin: '#9ccc4e',
    cloth: '#8c4a2f',
    accent: '#e8a33d',
    eye: '#ffd34e',
    head: { shape: 'long', ears: 'big', jaw: 'fangs', brow: 0.6 },
    weapon: 'club',
  },
  goblin_bomber: {
    id: 'goblin_bomber',
    height: 116,
    build: 'small',
    skin: '#6fa83a',
    cloth: '#4a4a52',
    accent: '#ff7a2f',
    eye: '#ff7a2f',
    head: { shape: 'long', ears: 'torn', jaw: 'fangs', brow: 0.4 },
    weapon: 'torch',
    offhand: 'orb',
  },
  hobgoblin: {
    id: 'hobgoblin',
    height: 138,
    build: 'lean',
    skin: '#c9743a',
    cloth: '#4e3a2c',
    metal: '#7f8894',
    accent: '#8e2f2f',
    eye: '#ffe36b',
    head: { shape: 'square', ears: 'pointy', jaw: 'fangs', gear: 'cap', brow: 0.5 },
    weapon: 'sword',
    offhand: 'buckler',
  },
  orc: {
    id: 'orc',
    height: 168,
    build: 'broad',
    skin: '#5c8f43',
    cloth: '#6b4326',
    accent: '#b03a2e',
    eye: '#ffdc5e',
    head: { shape: 'square', ears: 'pointy', jaw: 'tusks', brow: 0.7 },
    weapon: 'club',
  },
  orc_berserker: {
    id: 'orc_berserker',
    height: 174,
    build: 'broad',
    skin: '#8a5a3c',
    cloth: '#5c2f22',
    accent: '#e04b2a',
    eye: '#ff6b3d',
    head: { shape: 'square', ears: 'pointy', jaw: 'tusks', brow: 0.9, hair: '#2c1c14' },
    weapon: 'greataxe',
  },
  orc_warlord: {
    id: 'orc_warlord',
    height: 186,
    build: 'broad',
    skin: '#4f7d3c',
    cloth: '#3a2b22',
    metal: '#6f7885',
    accent: '#c9a227',
    eye: '#ffe36b',
    head: { shape: 'square', ears: 'pointy', jaw: 'tusks', gear: 'full', horns: 'small', brow: 0.8 },
    weapon: 'greatsword',
    cape: '#5c2029',
  },
  imp: {
    id: 'imp',
    height: 108,
    build: 'small',
    skin: '#c8402f',
    cloth: '#5a1f22',
    accent: '#ff9b3d',
    eye: '#ffd24e',
    glowEyes: true,
    head: { shape: 'long', ears: 'pointy', horns: 'small', jaw: 'fangs', brow: 0.6 },
    weapon: 'none',
    wings: 'bat',
  },
  shaman: {
    id: 'shaman',
    height: 136,
    build: 'lean',
    skin: '#6fa03c',
    cloth: '#4a2f5e',
    accent: '#a45cf0',
    eye: '#c98bff',
    glowEyes: true,
    head: { shape: 'long', ears: 'big', horns: 'small', gear: 'hood', brow: 0.3 },
    weapon: 'staff',
    aura: '#a45cf0',
  },
  troll: {
    id: 'troll',
    height: 196,
    build: 'huge',
    skin: '#6b7f52',
    cloth: '#4a3a2a',
    accent: '#8a6b3f',
    eye: '#f2c14e',
    head: { shape: 'square', ears: 'torn', jaw: 'tusks', horns: 'small', brow: 0.8 },
    weapon: 'club',
  },
  wraith: {
    id: 'wraith',
    height: 156,
    build: 'lean',
    skin: '#6a5f86',
    cloth: '#2b2340',
    accent: '#7d5cf0',
    eye: '#b39bff',
    glowEyes: true,
    head: { shape: 'skull', gear: 'hood', brow: 0.4 },
    weapon: 'scythe',
    cape: '#241d38',
  },
  demon_knight: {
    id: 'demon_knight',
    height: 190,
    build: 'broad',
    skin: '#8c3a3a',
    cloth: '#2a1c28',
    metal: '#4a3f52',
    accent: '#ff4d3d',
    eye: '#ff5a3d',
    glowEyes: true,
    head: { shape: 'square', horns: 'curved', jaw: 'fangs', gear: 'full', brow: 0.9 },
    weapon: 'greatsword',
    cape: '#3d1220',
  },
  shadow_fiend: {
    id: 'shadow_fiend',
    height: 120,
    build: 'broad',
    skin: '#3f2a33',
    cloth: '#2a1a22',
    accent: '#ff6a2f',
    eye: '#ff8a3d',
    glowEyes: true,
    head: { shape: 'long', ears: 'pointy', horns: 'small', jaw: 'fangs', brow: 0.9 },
    weapon: 'none',
  },
  demon_king: {
    id: 'demon_king',
    height: 260,
    build: 'huge',
    skin: '#8f2436',
    cloth: '#1d1220',
    metal: '#3b2f44',
    accent: '#ff3b30',
    eye: '#ffdd55',
    glowEyes: true,
    head: { shape: 'square', horns: 'crown', jaw: 'fangs', gear: 'crown', brow: 1 },
    weapon: 'greatsword',
    cape: '#4a0d1c',
    wings: 'bat',
    aura: '#ff3b30',
  },
};

/*
 * The two races that come with the Crown Pack.
 *
 * Elves and dwarves fight the way their homes made them: the elves reach,
 * the dwarves hold. The specs matter even for units with painted parts,
 * because the head crop on a card and the fallback rig both come from here.
 */
export const ALLY_ART: Record<string, CharacterSpec> = {
  elf_ranger: {
    id: 'elf_ranger',
    height: 168,
    build: 'lean',
    skin: '#f0d2b4',
    cloth: '#2f5d43',
    accent: '#a8e06a',
    eye: '#7fd8b0',
    head: { shape: 'long', ears: 'pointy', gear: 'none', brow: -0.35, hair: '#3b2f28' },
    weapon: 'bow',
    cape: '#274b38',
  },
  elf_spellweaver: {
    id: 'elf_spellweaver',
    height: 166,
    build: 'lean',
    skin: '#f4d9c0',
    cloth: '#3a4f8c',
    accent: '#9fd8ff',
    eye: '#9fd8ff',
    glowEyes: true,
    head: { shape: 'long', ears: 'pointy', gear: 'none', brow: -0.4, hair: '#e6e2d2' },
    weapon: 'staff',
    offhand: 'orb',
    aura: '#9fd8ff',
  },
  dwarf_warrior: {
    id: 'dwarf_warrior',
    height: 128,
    build: 'broad',
    skin: '#e0aa82',
    cloth: '#5a3a28',
    metal: '#b9c0cc',
    accent: '#d9a441',
    eye: '#4a3a2a',
    head: { shape: 'square', jaw: 'beard', gear: 'full', brow: 0.3, hair: '#8a4a22' },
    weapon: 'axe',
    offhand: 'shield',
  },
  dwarf_engineer: {
    id: 'dwarf_engineer',
    height: 126,
    build: 'broad',
    skin: '#e6b48c',
    cloth: '#4a4438',
    metal: '#8f9aa8',
    accent: '#e07a2c',
    eye: '#3a2f22',
    head: { shape: 'square', jaw: 'beard', gear: 'cap', brow: 0.2, hair: '#a05a28' },
    weapon: 'hammer',
  },
};

/* ------------------------------------------------------------------ heroes */

export const HERO_ART: Record<string, CharacterSpec> = {
  aldric: {
    id: 'aldric',
    height: 180,
    build: 'broad',
    skin: '#e6b189',
    cloth: '#26365c',
    metal: '#e8eef7',
    accent: '#f5c542',
    eye: '#4f8ae0',
    head: { shape: 'square', gear: 'plume', brow: -0.4, hair: '#d9c07a' },
    weapon: 'sword',
    offhand: 'shield',
    cape: '#2f6fb5',
    aura: '#ffe9a8',
  },
  seraphina: {
    id: 'seraphina',
    height: 170,
    build: 'lean',
    skin: '#f3ceab',
    cloth: '#3b2f6e',
    accent: '#7ce0ff',
    eye: '#8fe6ff',
    glowEyes: true,
    head: { shape: 'long', gear: 'none', brow: -0.3, hair: '#e9edf7' },
    weapon: 'staff',
    cape: '#5a49b5',
    wings: 'feather',
    aura: '#7ce0ff',
  },
};

export const ALL_CHARACTER_ART: Record<string, CharacterSpec> = {
  ...DEFENDER_ART,
  ...ALLY_ART,
  ...ENEMY_ART,
  ...HERO_ART,
};
